-- Python 知识图谱种子数据（22 章 + 136 知识点）
-- 【唯一数据源】知识点只存于 knowledge_node 表，后端代码不包含知识点列表
-- 用法: mysql -u root -p learning_agent < knowledge-seed.sql
-- 会先清空 knowledge_node 再写入；维护知识点请直接 UPDATE/INSERT knowledge_node
USE learning_agent;

TRUNCATE TABLE knowledge_node;

SET @subject = 'Python程序设计';

INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'Python 基础入门', 0, 1, 1, '[]', 'Python 基础入门');
SET @ch_1 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'Python 介绍与环境安装', @ch_1, 2, 2, '[]', 'Python 基础入门 · Python 介绍与环境安装');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '开发工具使用（IDLE、PyCharm、VS Code）', @ch_1, 2, 3, '[]', 'Python 基础入门 · 开发工具使用（IDLE、PyCharm、VS Code）');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '第一个 Python 程序', @ch_1, 2, 4, '[]', 'Python 基础入门 · 第一个 Python 程序');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '注释（单行、多行）', @ch_1, 2, 5, '[]', 'Python 基础入门 · 注释（单行、多行）');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '输入输出函数（input、print）', @ch_1, 2, 6, '[]', 'Python 基础入门 · 输入输出函数（input、print）');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '编码规范与命名规范', @ch_1, 2, 7, '[]', 'Python 基础入门 · 编码规范与命名规范');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '变量与数据类型', 0, 1, 8, '[]', '变量与数据类型');
SET @ch_2 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '变量定义与使用', @ch_2, 2, 9, '[]', '变量与数据类型 · 变量定义与使用');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '数字类型（int、float、bool）', @ch_2, 2, 10, '[]', '变量与数据类型 · 数字类型（int、float、bool）');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '字符串类型', @ch_2, 2, 11, '[]', '变量与数据类型 · 字符串类型');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '类型转换', @ch_2, 2, 12, '[]', '变量与数据类型 · 类型转换');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '标识符与关键字', @ch_2, 2, 13, '[]', '变量与数据类型 · 标识符与关键字');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '常量定义', @ch_2, 2, 14, '[]', '变量与数据类型 · 常量定义');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '运算符', 0, 1, 15, '[]', '运算符');
SET @ch_3 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '算术运算符', @ch_3, 2, 16, '[]', '运算符 · 算术运算符');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '赋值运算符', @ch_3, 2, 17, '[]', '运算符 · 赋值运算符');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '比较运算符', @ch_3, 2, 18, '[]', '运算符 · 比较运算符');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '逻辑运算符', @ch_3, 2, 19, '[]', '运算符 · 逻辑运算符');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '位运算符', @ch_3, 2, 20, '[]', '运算符 · 位运算符');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '成员运算符', @ch_3, 2, 21, '[]', '运算符 · 成员运算符');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '身份运算符', @ch_3, 2, 22, '[]', '运算符 · 身份运算符');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '运算符优先级', @ch_3, 2, 23, '[]', '运算符 · 运算符优先级');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '流程控制语句', 0, 1, 24, '[]', '流程控制语句');
SET @ch_4 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'if 条件语句', @ch_4, 2, 25, '[]', '流程控制语句 · if 条件语句');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'if-else 语句', @ch_4, 2, 26, '[]', '流程控制语句 · if-else 语句');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'if-elif-else 多分支', @ch_4, 2, 27, '[]', '流程控制语句 · if-elif-else 多分支');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'while 循环', @ch_4, 2, 28, '[]', '流程控制语句 · while 循环');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'for 循环', @ch_4, 2, 29, '[]', '流程控制语句 · for 循环');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'break、continue、pass', @ch_4, 2, 30, '[]', '流程控制语句 · break、continue、pass');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '循环嵌套', @ch_4, 2, 31, '[]', '流程控制语句 · 循环嵌套');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '三目运算符', @ch_4, 2, 32, '[]', '流程控制语句 · 三目运算符');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '字符串', 0, 1, 33, '[]', '字符串');
SET @ch_5 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '字符串定义与特性', @ch_5, 2, 34, '[]', '字符串 · 字符串定义与特性');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '字符串索引与切片', @ch_5, 2, 35, '[]', '字符串 · 字符串索引与切片');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '字符串常用方法', @ch_5, 2, 36, '[]', '字符串 · 字符串常用方法');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '字符串格式化', @ch_5, 2, 37, '[]', '字符串 · 字符串格式化');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '转义字符', @ch_5, 2, 38, '[]', '字符串 · 转义字符');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '字符串拼接与分割', @ch_5, 2, 39, '[]', '字符串 · 字符串拼接与分割');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '字符串判断方法', @ch_5, 2, 40, '[]', '字符串 · 字符串判断方法');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '列表（List）', 0, 1, 41, '[]', '列表（List）');
SET @ch_6 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '列表定义与特性', @ch_6, 2, 42, '[]', '列表（List） · 列表定义与特性');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '增删改查', @ch_6, 2, 43, '[]', '列表（List） · 增删改查');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '列表遍历', @ch_6, 2, 44, '[]', '列表（List） · 列表遍历');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '列表嵌套', @ch_6, 2, 45, '[]', '列表（List） · 列表嵌套');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '常用方法', @ch_6, 2, 46, '[]', '列表（List） · 常用方法');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '列表推导式', @ch_6, 2, 47, '[]', '列表（List） · 列表推导式');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '元组（Tuple）', 0, 1, 48, '[]', '元组（Tuple）');
SET @ch_7 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '元组定义与特性', @ch_7, 2, 49, '[]', '元组（Tuple） · 元组定义与特性');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '元组操作', @ch_7, 2, 50, '[]', '元组（Tuple） · 元组操作');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '元组与列表区别', @ch_7, 2, 51, '[]', '元组（Tuple） · 元组与列表区别');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '字典（Dict）', 0, 1, 52, '[]', '字典（Dict）');
SET @ch_8 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '字典定义与特性', @ch_8, 2, 53, '[]', '字典（Dict） · 字典定义与特性');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '键值对操作', @ch_8, 2, 54, '[]', '字典（Dict） · 键值对操作');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '增删改查', @ch_8, 2, 55, '[]', '字典（Dict） · 增删改查');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '字典遍历', @ch_8, 2, 56, '[]', '字典（Dict） · 字典遍历');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '常用方法', @ch_8, 2, 57, '[]', '字典（Dict） · 常用方法');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '字典推导式', @ch_8, 2, 58, '[]', '字典（Dict） · 字典推导式');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '集合（Set）', 0, 1, 59, '[]', '集合（Set）');
SET @ch_9 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '集合定义与特性', @ch_9, 2, 60, '[]', '集合（Set） · 集合定义与特性');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '增删改查', @ch_9, 2, 61, '[]', '集合（Set） · 增删改查');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '交集、并集、差集', @ch_9, 2, 62, '[]', '集合（Set） · 交集、并集、差集');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '去重应用', @ch_9, 2, 63, '[]', '集合（Set） · 去重应用');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '函数基础', 0, 1, 64, '[]', '函数基础');
SET @ch_10 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '函数定义与调用', @ch_10, 2, 65, '[]', '函数基础 · 函数定义与调用');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '参数（形参、实参）', @ch_10, 2, 66, '[]', '函数基础 · 参数（形参、实参）');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '位置参数、关键字参数', @ch_10, 2, 67, '[]', '函数基础 · 位置参数、关键字参数');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '默认参数', @ch_10, 2, 68, '[]', '函数基础 · 默认参数');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '不定长参数', @ch_10, 2, 69, '[]', '函数基础 · 不定长参数');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '返回值 return', @ch_10, 2, 70, '[]', '函数基础 · 返回值 return');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '函数嵌套', @ch_10, 2, 71, '[]', '函数基础 · 函数嵌套');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '作用域（全局、局部）', @ch_10, 2, 72, '[]', '函数基础 · 作用域（全局、局部）');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '递归函数', @ch_10, 2, 73, '[]', '函数基础 · 递归函数');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '高级函数', 0, 1, 74, '[]', '高级函数');
SET @ch_11 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'lambda 匿名函数', @ch_11, 2, 75, '[]', '高级函数 · lambda 匿名函数');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'map、filter、reduce', @ch_11, 2, 76, '[]', '高级函数 · map、filter、reduce');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '闭包', @ch_11, 2, 77, '[]', '高级函数 · 闭包');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '装饰器', @ch_11, 2, 78, '[]', '高级函数 · 装饰器');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '偏函数', @ch_11, 2, 79, '[]', '高级函数 · 偏函数');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '文件操作', 0, 1, 80, '[]', '文件操作');
SET @ch_12 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '文件打开与关闭', @ch_12, 2, 81, '[]', '文件操作 · 文件打开与关闭');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '读文件、写文件', @ch_12, 2, 82, '[]', '文件操作 · 读文件、写文件');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '上下文管理器 with', @ch_12, 2, 83, '[]', '文件操作 · 上下文管理器 with');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'os 模块操作文件路径', @ch_12, 2, 84, '[]', '文件操作 · os 模块操作文件路径');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '批量文件处理', @ch_12, 2, 85, '[]', '文件操作 · 批量文件处理');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '异常处理', 0, 1, 86, '[]', '异常处理');
SET @ch_13 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '异常概念', @ch_13, 2, 87, '[]', '异常处理 · 异常概念');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'try-except', @ch_13, 2, 88, '[]', '异常处理 · try-except');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'else、finally', @ch_13, 2, 89, '[]', '异常处理 · else、finally');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '异常传递', @ch_13, 2, 90, '[]', '异常处理 · 异常传递');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '主动抛出异常 raise', @ch_13, 2, 91, '[]', '异常处理 · 主动抛出异常 raise');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '自定义异常', @ch_13, 2, 92, '[]', '异常处理 · 自定义异常');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '模块与包', 0, 1, 93, '[]', '模块与包');
SET @ch_14 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '模块概念', @ch_14, 2, 94, '[]', '模块与包 · 模块概念');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'import 导入', @ch_14, 2, 95, '[]', '模块与包 · import 导入');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'from ... import', @ch_14, 2, 96, '[]', '模块与包 · from ... import');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '自定义模块', @ch_14, 2, 97, '[]', '模块与包 · 自定义模块');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '包（Package）', @ch_14, 2, 98, '[]', '模块与包 · 包（Package）');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '__init__.py', @ch_14, 2, 99, '[]', '模块与包 · __init__.py');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '第三方库安装（pip）', @ch_14, 2, 100, '[]', '模块与包 · 第三方库安装（pip）');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '面向对象编程 OOP', 0, 1, 101, '[]', '面向对象编程 OOP');
SET @ch_15 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '类与对象', @ch_15, 2, 102, '[]', '面向对象编程 OOP · 类与对象');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '属性与方法', @ch_15, 2, 103, '[]', '面向对象编程 OOP · 属性与方法');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '构造函数 __init__', @ch_15, 2, 104, '[]', '面向对象编程 OOP · 构造函数 __init__');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '析构函数 __del__', @ch_15, 2, 105, '[]', '面向对象编程 OOP · 析构函数 __del__');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '封装', @ch_15, 2, 106, '[]', '面向对象编程 OOP · 封装');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '继承', @ch_15, 2, 107, '[]', '面向对象编程 OOP · 继承');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '方法重写', @ch_15, 2, 108, '[]', '面向对象编程 OOP · 方法重写');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '多态', @ch_15, 2, 109, '[]', '面向对象编程 OOP · 多态');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '类属性、实例属性', @ch_15, 2, 110, '[]', '面向对象编程 OOP · 类属性、实例属性');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '静态方法、类方法', @ch_15, 2, 111, '[]', '面向对象编程 OOP · 静态方法、类方法');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '魔术方法', @ch_15, 2, 112, '[]', '面向对象编程 OOP · 魔术方法');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'property 装饰器', @ch_15, 2, 113, '[]', '面向对象编程 OOP · property 装饰器');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '正则表达式', 0, 1, 114, '[]', '正则表达式');
SET @ch_16 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '正则基础语法', @ch_16, 2, 115, '[]', '正则表达式 · 正则基础语法');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 're 模块', @ch_16, 2, 116, '[]', '正则表达式 · re 模块');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '匹配、查找、替换', @ch_16, 2, 117, '[]', '正则表达式 · 匹配、查找、替换');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '分组、贪婪模式', @ch_16, 2, 118, '[]', '正则表达式 · 分组、贪婪模式');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '数据库编程', 0, 1, 119, '[]', '数据库编程');
SET @ch_17 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '数据库基础', @ch_17, 2, 120, '[]', '数据库编程 · 数据库基础');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'MySQL 安装', @ch_17, 2, 121, '[]', '数据库编程 · MySQL 安装');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'pymysql 使用', @ch_17, 2, 122, '[]', '数据库编程 · pymysql 使用');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '增删改查', @ch_17, 2, 123, '[]', '数据库编程 · 增删改查');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '事务处理', @ch_17, 2, 124, '[]', '数据库编程 · 事务处理');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'SQL 注入防护', @ch_17, 2, 125, '[]', '数据库编程 · SQL 注入防护');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '网络编程', 0, 1, 126, '[]', '网络编程');
SET @ch_18 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'HTTP 协议', @ch_18, 2, 127, '[]', '网络编程 · HTTP 协议');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'requests 库', @ch_18, 2, 128, '[]', '网络编程 · requests 库');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '接口请求', @ch_18, 2, 129, '[]', '网络编程 · 接口请求');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'JSON 解析', @ch_18, 2, 130, '[]', '网络编程 · JSON 解析');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'WebSocket 通信', @ch_18, 2, 131, '[]', '网络编程 · WebSocket 通信');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '并发编程', 0, 1, 132, '[]', '并发编程');
SET @ch_19 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '多线程', @ch_19, 2, 133, '[]', '并发编程 · 多线程');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '多进程', @ch_19, 2, 134, '[]', '并发编程 · 多进程');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '协程 asyncio', @ch_19, 2, 135, '[]', '并发编程 · 协程 asyncio');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '异步编程', @ch_19, 2, 136, '[]', '并发编程 · 异步编程');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'Web 开发（Flask）', 0, 1, 137, '[]', 'Web 开发（Flask）');
SET @ch_20 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, 'Flask 框架基础', @ch_20, 2, 138, '[]', 'Web 开发（Flask） · Flask 框架基础');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '路由', @ch_20, 2, 139, '[]', 'Web 开发（Flask） · 路由');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '视图函数', @ch_20, 2, 140, '[]', 'Web 开发（Flask） · 视图函数');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '请求与响应', @ch_20, 2, 141, '[]', 'Web 开发（Flask） · 请求与响应');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '模板渲染', @ch_20, 2, 142, '[]', 'Web 开发（Flask） · 模板渲染');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '接口开发', @ch_20, 2, 143, '[]', 'Web 开发（Flask） · 接口开发');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '跨域处理', @ch_20, 2, 144, '[]', 'Web 开发（Flask） · 跨域处理');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '项目模块化', @ch_20, 2, 145, '[]', 'Web 开发（Flask） · 项目模块化');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '数据处理', 0, 1, 146, '[]', '数据处理');
SET @ch_21 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '数据清洗', @ch_21, 2, 147, '[]', '数据处理 · 数据清洗');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '数据统计', @ch_21, 2, 148, '[]', '数据处理 · 数据统计');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '数据分析基础', @ch_21, 2, 149, '[]', '数据处理 · 数据分析基础');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '字典、列表数据处理', @ch_21, 2, 150, '[]', '数据处理 · 字典、列表数据处理');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '项目实战必备', 0, 1, 151, '[]', '项目实战必备');
SET @ch_22 = LAST_INSERT_ID();
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '项目结构规范', @ch_22, 2, 152, '[]', '项目实战必备 · 项目结构规范');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '日志配置', @ch_22, 2, 153, '[]', '项目实战必备 · 日志配置');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '配置文件管理', @ch_22, 2, 154, '[]', '项目实战必备 · 配置文件管理');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '接口封装', @ch_22, 2, 155, '[]', '项目实战必备 · 接口封装');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '工具类封装', @ch_22, 2, 156, '[]', '项目实战必备 · 工具类封装');
INSERT INTO knowledge_node (subject, node_name, parent_id, node_level, sort_order, prerequisite_ids, description) VALUES (@subject, '项目部署', @ch_22, 2, 157, '[]', '项目实战必备 · 项目部署');

-- 前置关系由后端首次启动或 KnowledgeGraphService 维护；空库直接启动后端也会自动链式设置。